### ISSUE TITLE
Add theme selection

### ISSUE THREAD

**Issue by AndydeCleyre** [AndydeCleyre/colorcodebot#1]
The `highlight` tool offers 88 themes. Let's choose a subset to offer.

Update:
previews removed
outdated anyway since moving to pygments, which offers much fewer themes

**Comment by kirsan31** [comment]
Are this themes per language, or system wide?

**Comment by AndydeCleyre** [comment]
@kirsan31 each theme would apply to all languages.

But now we're using pygments for images, and so will probably use it for html instead of `highlight`, so there will only be a handful of themes available.

I'll update tonight.

**Comment by kirsan31** [comment]
I use/like VS (2017 now) themes. So, I think closest one, will be:
![image](https://user-images.githubusercontent.com/17767561/39050746-288e909e-44af-11e8-8536-63273cb99a6a.png)

**Comment by Piterden** [comment]
Fuck!!! Remove those images, @AndydeCleyre !!  We believe you...
