### ISSUE TITLE
Add x86-64 assembly instruction set highlight.

### ISSUE THREAD

**Issue by nikolaytihonov** [AndydeCleyre/colorcodebot#14]
Please implement syntax highlighting for GNU Assembler AT&T or Intel

**Comment by AndydeCleyre** [comment]
This project could use a revisit from me, regarding its build system and hosting provider, and I hope to devote some time and attention to it soon. But it may be a couple weeks.

---

Currently it uses [pygments](https://pygments.org/languages/) to generate the colorized output. It has a decent range of syntax support, is easy to use in a python project, and provides the two types of output we want (html and png) using the same set of themes.

If you click the link above and check the supported syntax list, you'll see an item for [NASM](https://www.nasm.us/). Is that an appropriate match for your use? I think it will be suitable. If so, it'll be easy to add soon.

**Comment by AndydeCleyre** [comment]
Just an info update: pygments is no longer used here, in favor of the lua project called highlight. It supports `asm` as well, just let me know if anything seems off.
