### ISSUE TITLE
Add image output

### ISSUE THREAD

**Issue by AndydeCleyre** [AndydeCleyre/colorcodebot#2]
Suggestions welcome.

- Always provide image (in addition to html)?
- Send image "as file" (uncompressed) when code is `> x` lines. `80` for now.
- Use pygments

**Comment by kirsan31** [comment]
I think image (if ever needed) must be optional.

**Comment by AndydeCleyre** [comment]
@kirsan31 I'm closing this, as there's now image output, and you don't lose anything by getting the image even though you personally don't need it (right?).

If the unwanted image is really annoying, please open a new issue.
