### ISSUE TITLE
Ensure HTML is rendered with the "system standard" monospace font on macOS, or at least some monospace font

### ISSUE THREAD

**Issue by AndydeCleyre** [AndydeCleyre/colorcodebot#20]
We're currently setting font in CSS to `monospace,mono,ui-monospace`, but there's at least one report of proportional fonts being used by all browsers on macOS.

**Comment by AndydeCleyre** [comment]
I found two testers with macOS but they couldn't reproduce the issue.

Friendly ping to @marcotrosi to let me know if any more info can be provided.

**Comment by marcotrosi** [comment]
> I found two testers with macOS but they couldn't reproduce the issue.
> 
> Friendly ping to @marcotrosi to let me know if any more info can be provided.

Let me know what you need

**Comment by AndydeCleyre** [comment]
Can you let me know, on [this page](https://www.w3.org/Style/Examples/007/fonts.en.html) at the line starting with "monospace" (just before the "cursive" section), what font is used for you?

If it's not a mono font, what's the browser+version?

---

Anyway, I just added a bunch of 'web-safe' fallback font families, so please give the bot another try and let me know how it goes.

If it's working for you, feel free to suggest a re-order of these (list is in the current fallback order):

- monaco
- Consolas
- Andale Mono,AndaleMono
- Lucida Console
- Lucida Sans Typewriter
- Lucida Typewriter
- Courier New
- Courier
- Bitstream Vera Sans Mono

---

Thanks!

**Comment by marcotrosi** [comment]
Both monofont now. On the page you linked and I tested the bot and my browser now uses a monofont for displaying. Thx
