### ISSUE TITLE
Consider: Drop HTML output

### ISSUE THREAD

**Issue by AndydeCleyre** [AndydeCleyre/colorcodebot#40]
Now that the bot has group listening mode, the HTML output may not be worth much.

**Comment by vangquan** [comment]
Instead, I would request to keep the HTML output option without the line number. I mean, HTML is an option that can copy text from.

**Comment by AndydeCleyre** [comment]
Thanks for the feedback! I was thinking of using the HTML with the more recent bot API feature of embedding a little website...


But the HTML as it is should allow you to easily select the content without the line numbers. Does it behave differently for you?

**Comment by AndydeCleyre** [comment]
Now that Telegram itself offers some code highlighting of the selectable message content, I'm even more inclined to drop the HTML output.

There has been no comment here in over a year, so will soon go ahead with this, but please do chime in if that is still a worthwhile feature for you.

**Comment by AndydeCleyre** [comment]
Aaaand it's dropped.
