### ISSUE TITLE
Emojis missed in code to image 

### ISSUE THREAD

**Issue by FairyPenguin** [AndydeCleyre/colorcodebot#43]
When I post a code snippet with emojis the output image is missing those emojis 

Example:
`/* Panic function 
Write a PANIC! function. The function should take in a sentence and return the same
sentence in all caps with an exclamation point (!) at the end. Use JavaScript's
built in string methods. 

If the string is a phrase or sentence, add a 😱 emoji in between each word. 

Example input: "Hello"
Example output: "HELLO!"

Example input: "I'm almost out of coffee"
Example output: "I'M 😱 ALMOST 😱 OUT 😱 OF 😱 COFFEE!"

.split() .join()
*/

//Solution

// Test your function
console.log(panic("I'm almost out of coffee"));
console.log(panic("winter is coming"));
console.log(panic("hello"));`

Output screenshot:
![image](https://user-images.githubusercontent.com/37639473/205365577-3fe01937-8b62-4c23-8170-8ea8d7d9374f.png)

**Comment by AndydeCleyre** [comment]
Thanks!

Please use markdown code fences in comments here to preserve your code. As it is, GitHub is rewriting your emojis, making it hard to copy and paste accurately.

I think this is now resolved with some changes I've just pushed and deployed.
![EMOJIWORK](https://user-images.githubusercontent.com/1787385/205410527-58453811-2b26-4080-9fc8-02981a28e8d1.jpg)
