### ISSUE TITLE
[feature-request] Add font selection

### ISSUE THREAD

**Issue by Piterden** [AndydeCleyre/colorcodebot#5]
If we use HTML why don't make it able to select a font for render?

**Comment by AndydeCleyre** [comment]
The HTML output should use whatever your browser's default monospace font is. So just set your browser to use the font you want.

**Comment by AndydeCleyre** [comment]
Depending on your system, that may rely on the configuration at `~/.config/fontconfig/fonts.conf`.

**Comment by AndydeCleyre** [comment]
There's now an example fontconfig file (which is used by the current deployment) at [app/.fontconfig/fonts.conf](https://github.com/AndydeCleyre/colorcodebot/blob/develop/app/.fontconfig/fonts.conf).
